all:
	g++ -std=c++0x -lm -O2 -Wall -Wextra -Wno-unused-const-variable -D_GEANY -o client client.cpp -pthread -fopenmp
	g++ -std=c++0x -lm -O2 -Wall -Wextra -Wno-unused-const-variable -D_GEANY -o life life.cpp -pthread -fopenmp
